local opt = vim.opt

opt.clipboard = "unnamedplus"
opt.colorcolumn = "120"
opt.completeopt = "menu,menuone,noselect"
opt.confirm = true
opt.expandtab = true
opt.hidden = true
opt.ignorecase = true
opt.inccommand = "nosplit"
opt.incsearch = true
opt.iskeyword:append("-")
opt.joinspaces = false
opt.linebreak = true
opt.mouse = ""
opt.number = true
opt.pumblend = 15 -- (p)op(u)p(m)enu(blend)
opt.ruler = false
opt.scrolloff = 12
opt.shiftwidth = 4
opt.sidescrolloff = 4
opt.smartcase = true
opt.softtabstop = 4
opt.splitbelow = true
opt.splitright = true
opt.tabstop = 4
opt.termguicolors = true
opt.timeout = true
opt.timeoutlen = 300
opt.wildmode = { "longest", "full" }
opt.wrap = true
